
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/car-db?createDatabaseIfNotExist=true&severTimezone=UTC"
    username: "root"
    password: "root"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57Dialect"